[package]
name = "timer"
version = "0.1.0"
edition = "2021"

[dependencies]
smallvec = { version = "1.13.2", features = ["const_generics", "const_new"] }

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "timer_bench"
harness = false